[package]
name = "write-partitioned-parquet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datafusion = "13.0.0"
tokio = "1.21.2"